name: Zip Package and Post Release on Slack

on:
  push:
    branches:
      - main

jobs:
  create-zip:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '--package')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get commit hash
      id: get-commit-hash
      run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Create zip file
      run: zip -r "${{ github.repository_owner }}_${{ github.event.repository.name }}-${{ steps.get-commit-hash.outputs.commit_hash }}.mcworld" .

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        name: ${{ github.event.repository.name }} ${{ steps.get-commit-hash.outputs.commit_hash }}
        tag_name: ${{ steps.get-commit-hash.outputs.commit_hash }}
        draft: false
        prerelease: false
        files: "${{ github.repository_owner }}_${{ github.event.repository.name }}-${{ steps.get-commit-hash.outputs.commit_hash }}.mcworld"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Slack Notification
      uses: homeday-de/slack-release-bot-action@main
      with:
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        title: 📦 ${{ github.event.repository.name }} release ${{ steps.get-commit-hash.outputs.commit_hash }}
        body: ${{ github.event.head_commit.message }}\n\n\n<https://github.com/${{ github.repository }}/releases/download/${{ steps.get-commit-hash.outputs.commit_hash }}/${{ github.repository_owner }}_${{ github.event.repository.name }}-${{ steps.get-commit-hash.outputs.commit_hash }}.mcworld|🔗 Download for this release>
        context: Based on commit by ${{ github.event.head_commit.author.name }}
